import mongoose from 'mongoose';

/**
 * Monthly payroll record per staff member.
 * Generated by the payroll service — immutable once status is 'paid'.
 */
const payrollSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    profile: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'StaffProfile',
    },

    // Period
    month: { type: Number, required: true, min: 1, max: 12 },
    year: { type: Number, required: true },

    // Attendance summary
    workingDays: { type: Number, default: 0 },   // scheduled days in month
    presentDays: { type: Number, default: 0 },
    absentDays: { type: Number, default: 0 },
    lateDays: { type: Number, default: 0 },
    leaveDays: { type: Number, default: 0 },
    totalNetHours: { type: Number, default: 0 },
    totalOvertimeHours: { type: Number, default: 0 },

    // Earnings
    basePay: { type: Number, required: true },
    overtimePay: { type: Number, default: 0 },
    bonus: { type: Number, default: 0 },
    grossPay: { type: Number, required: true },

    // Deductions
    taxDeduction: { type: Number, default: 0 },
    absenceDeduction: { type: Number, default: 0 },
    otherDeductions: { type: Number, default: 0 },
    totalDeductions: { type: Number, default: 0 },

    // Net
    netPay: { type: Number, required: true },
    currency: { type: String, default: 'NPR' },

    // Status
    status: {
      type: String,
      enum: ['draft', 'approved', 'paid'],
      default: 'draft',
    },
    approvedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    approvedAt: { type: Date },
    paidAt: { type: Date },

    notes: { type: String, trim: true },
  },
  { timestamps: true }
);

// One payroll record per user per month/year
payrollSchema.index({ user: 1, month: 1, year: 1 }, { unique: true });

export default mongoose.model('Payroll', payrollSchema);
